version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://app_user@postgres/bandsindex
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: bandsindex